name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  manual_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manual approval
        id: approval
        run: |
          echo "Approve the deployment (Reply with 'approve' or 'reject')"
          echo "APPROVAL_STATUS=pending" >> $GITHUB_ENV

          while read -r comment; do
            if [[ $comment == "approve" ]]; then
              echo "APPROVAL_STATUS=approved" >> $GITHUB_ENV
              break
            elif [[ $comment == "reject" ]]; then
              echo "APPROVAL_STATUS=rejected" >> $GITHUB_ENV
              break
            fi
          done < <(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" | jq -r '.[].body')


  deploy:
    needs: manual_approval
    if: needs.manual_approval.outputs.approval_status == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ github.workspace }}" ec2-user@50.17.57.13:~/website/

      - name: SSH into EC2
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@50.17.57.13 "sudo cp -r ~/website/mywebsite/* /var/www/html"
