name: Deployment

on:
  push:
    branches:
      - master

jobs:
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Approval Message
        run: |
          echo "Please review and approve this deployment."
          echo "To approve, set the 'approved' output to 'true' using '::set-output name=approved::true'"
          echo "To reject, set the 'approved' output to 'false' using '::set-output name=approved::false'"

      - name: Wait for Approval
        id: verify_approver
        uses: actions/github-script@v4
        with:
          script: |
            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const approvalComment = comments.find(comment =>
              (comment.user.login === context.repo.owner || comment.user.login === 'mutuwa99') &&
              (comment.body.includes('/approve') || comment.body.includes('/reject'))
            );

            if (approvalComment && approvalComment.body.includes('/approve')) {
              console.log('Approved');
              core.setOutput('approved', 'true');
            } else if (approvalComment && approvalComment.body.includes('/reject')) {
              console.log('Rejected');
              core.setOutput('approved', 'false');
            } else {
              console.log('No decision');
              core.setOutput('approved', 'false');
            }

            if (approvalComment) {
              await github.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: approvalComment.id,
                content: 'rocket' // You can use any GitHub reaction emoji here
              });
            }

  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: manual-approval
    # if: github.ref == 'refs/heads/master' && needs.manual-approval.outputs.approved == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production Environment
        uses: appleboy/scp-action@v2
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: ./
          target: /var/www/html/
