name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  manual_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manual approval
        id: approval
        run: |
          echo "Approve the deployment (Reply with 'approve' or 'reject')"

          # Send approval request email
          response=$(curl -s -X POST -H "Content-Type: application/json" \
                      -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
                      -d '{
                            "personalizations": [
                              {"to": [{"email": "isayamulaudzi@gmail.com"}]}
                            ],
                            "from": {"email": "noreply@yourdomain.com"},
                            "subject": "Deployment Approval",
                            "content": [
                              {"type": "text/plain", "value": "Please approve or reject the deployment by replying to this email with 'approve' or 'reject'."}
                            ],
                            "mail_settings": {"sandbox_mode": {"enable": true}}
                          }' \
                      "https://api.sendgrid.com/v3/mail/send")

          # Check if the email was sent successfully
          status=$(echo "$response" | grep -o '"status": *[^,}]*' | awk -F':' '{print $2}' | tr -d '[:space:]')

          if [[ $status == "202" ]]; then
            echo "::set-output name=approval_status::pending"
          else
            echo "::set-output name=approval_status::rejected"
          fi

  send_approval_email:
    needs: manual_approval
    runs-on: ubuntu-latest
    if: needs.manual_approval.outputs.approval_status == 'pending'
    steps:
      - name: Send approval email
        uses: dawidd6/action-send-email@v2
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: Deployment Approval
          to: isayamulaudzi@gmail.com
          from: noreply@yourdomain.com
          body: Please approve or reject the deployment by replying to this email with 'approve' or 'reject'.         
          


  deploy:
    needs: send_approval_email
    if: needs.send_approval_email.outputs.status == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ github.workspace }}" ec2-user@50.17.57.13:~/website/

      - name: SSH into EC2
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@50.17.57.13 "sudo cp -r ~/website/mywebsite/* /var/www/html"
