name: Deployment

on:
  push:
    branches:
      - master

jobs:
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Approval Message
        run: |
          echo "Please review and approve this deployment."
          echo "To approve, set the 'approved' output to 'true' using '::set-output name=approved::true'"
          echo "To reject, set the 'approved' output to 'false' using '::set-output name=approved::false'"

      - name: Wait for Approval
        id: verify_approver
        uses: actions/github-script@v4
   

  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: manual-approval
    # if: github.ref == 'refs/heads/master' && needs.manual-approval.outputs.approved == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production Environment
        uses: appleboy/scp-action@v2
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: ./
          target: /var/www/html/
