on:
  push:
    branches:
      - master

jobs:
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Approver
        id: verify_approver
        run: echo "::set-output name=approved::${{ github.actor == 'mutuwa99' }}"

      - name: Manual Approval
        if: steps.verify_approver.outputs.approved == 'false'
        run: |
          echo "Manual approval required. Please approve or reject this deployment."
          echo "To approve, add a comment on the associated issue: ${{ github.event.issue.html_url }}"
          echo "To reject, add a comment starting with 'Reject' on the associated issue: ${{ github.event.issue.html_url }}"
          exit 1

  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: manual-approval
#     if: github.ref == 'refs/heads/master' && needs.manual-approval.outputs.approved == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add necessary steps to build and prepare your application for deployment

      - name: Deploy to Production Environment
        uses: webfactory/ssh-agent@v0.5.1
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            # Change to the appropriate directory on the remote server
            cd /var/www/html

            # Copy the application files from the GitHub Actions workspace to the remote server
            cp -r $GITHUB_WORKSPACE/* .
