name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-production:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master' && needs.manual-approval.outputs.approved == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production Environment
        uses: appleboy/scp-action@v2
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: ./
          target: /var/www/html/
